### PR TITLE
C4 310 & 256 Mitigation

### PR DESCRIPTION
**Pull request by rayeaster**
address https://github.com/code-423n4/2023-10-badger-findings/issues/310 & https://github.com/code-423n4/2023-10-badger-findings/issues/256 by adding extra checks around `PriceFeed` state machine if fallback oracle is empty (not set) and CL reports 50% deviation between rounds

- Additional checks in `_bothOraclesLiveAndUnbrokenAndSimilarPrice()` & `_bothOraclesSimilarPrice()` to distinguish the situations when fallback is set (broken/frozen) AND when fallback is not set at all
- Ensure only change to `usingChainlinkFallbackUntrusted` if CL reports pass the max deviation check in status `bothOraclesUntrusted` ( `case 3` in the `PriceFeed` state machine)
- Ensure correct state and price returned if CL reports doesn't pass the max deviation check in status `usingFallbackChainlinkFrozen` ( `case 4` in the `PriceFeed` state machine)
- Ensue above similarity comparison (`_bothOraclesLiveAndUnbrokenAndSimilarPrice()` or `_bothOraclesSimilarPrice()`) between primary & fallback oracle happens **ONLY AFTER** other single-source checks have passed (bad/frozen/max-deviation) in each status

### CODE REVIEW

**Comment by rayeaster** [comment]
> l am not sure if this is even possible when chainlink is frozen, but l would rather ask than keep it to myself.
> 
> * Take as example that the system is in state **usingFallbackChainlinkFrozen**, basically the system checks if chainlink is broken, frozen and if not it checks if the fallback is broken and changes the status to **usingChainlinkFallbackUntrusted** and uses the latest answer from chainlink. One thing l noticed is that along with checking if chainlink is broken or frozen, the system misses to check if the prev and current price of chainlink changes above the max. So in theory if this every happens instead of switching to **bothOraclesUntrusted** and using the **lastGoodPrice**, the system will use the chainlink answer and switch to **usingChainlinkFallbackUntrusted**.
> 
> ```solidity
>         // --- CASE 4: Using Fallback, and Chainlink is frozen ---
>         if (status == Status.usingFallbackChainlinkFrozen) {
>             if (_chainlinkIsBroken(chainlinkResponse, prevChainlinkResponse)) {
>                 // If both Oracles are broken, return last good price
>                 if (_fallbackIsBroken(fallbackResponse)) {
>                     _changeStatus(Status.bothOraclesUntrusted);
>                     return lastGoodPrice;
>                 }
> 
>                 // If Chainlink is broken, remember it and switch to using Fallback
>                 _changeStatus(Status.usingFallbackChainlinkUntrusted);
> 
>                 if (_fallbackIsFrozen(fallbackResponse)) {
>                     return lastGoodPrice;
>                 }
> 
>                 // If Fallback is working, return Fallback current price
>                 return _storeFallbackPrice(fallbackResponse);
>             }
> 
>             if (_chainlinkIsFrozen(chainlinkResponse)) {
>                 // if Chainlink is frozen and Fallback is broken, remember Fallback broke, and return last good price
>                 if (_fallbackIsBroken(fallbackResponse)) {
>                     _changeStatus(Status.usingChainlinkFallbackUntrusted);
>                     return lastGoodPrice;
>                 }
> 
>                 // If both are frozen, just use lastGoodPrice
>                 if (_fallbackIsFrozen(fallbackResponse)) {
>                     return lastGoodPrice;
>                 }
> 
>                 // if Chainlink is frozen and Fallback is working, keep using Fallback (no status change)
>                 return _storeFallbackPrice(fallbackResponse);
>             }
> 
>             // if Chainlink is live and Fallback is broken, remember Fallback broke, and return Chainlink price
>             if (_fallbackIsBroken(fallbackResponse)) {
>                 _changeStatus(Status.usingChainlinkFallbackUntrusted);
>                 return _storeChainlinkPrice(chainlinkResponse.answer);
>             }
> 
>             // If Chainlink is live and Fallback is frozen, just use last good price (no status change) since we have no basis for comparison
>             if (_fallbackIsFrozen(fallbackResponse)) {
>                 return lastGoodPrice;
>             }
> 
>             // If Chainlink is live and Fallback is working, compare prices. Switch to Chainlink
>             // if prices are within 5%, and return Chainlink price.
>             if (_bothOraclesSimilarPrice(chainlinkResponse, fallbackResponse)) {
>                 _changeStatus(Status.chainlinkWorking);
>                 return _storeChainlinkPrice(chainlinkResponse.answer);
>             }
> 
>             // Otherwise if Chainlink is live but price not within 5% of Fallback, distrust Chainlink, and return Fallback price
>             _changeStatus(Status.usingFallbackChainlinkUntrusted);
>             return _storeFallbackPrice(fallbackResponse);
>         }
> ```

according to Liquity doc, it seems ok 
https://docs.google.com/spreadsheets/d/18fdtTUoqgmsK3Mb6LBO-6na0oK-Y9LWBqnPCJRp5Hsg/edit#gid=316701608
image

**Comment by GalloDaSballo** [comment]
What is 256 saying that was worth fixing?

**Comment by GalloDaSballo** [comment]
@wtj2021 it could be good to write the following (fuzz or invariant)

`fetchPrice` can never return a different price when called twice or three times in a row

Basically adapt `EchidnaPriceFeedTester` to have that check, can work on this tomorrow if you don't have the bandwith

**Comment by rayeaster** [comment]
@CodingNameKiki I think the issue you mentioned around both primary and fallback are frozen and the code decide to choose fallback over primary is valid. However, what I am not quite sure about is whether we should change the behavior. 

Considering `usingFallbackChainlinkFrozen` is the **only** proper status indicating primary (CL) is frozen (but not broken), and Liquity also clearly states in both the code comment and its design doc that "If Fallback is frozen or working, remember Chainlink froze, and switch to Fallback", it might be acceptable to keep it untouched.

image

**Comment by rayeaster** [comment]
would love to have @dapp-whisperer @GalloDaSballo @wtj2021 insights on this topic

**Comment by dapp-whisperer** [comment]
> When both oracles were in frozen state but are back alive and there is 5% difference in the prices, the system naturally selects the response of the fallback oracle as more accurate even tho chainlink is the primary oracle.

I think this is acceptable due to the threshold.
I agree with Kiki that it's not desired behavior - a great find.
I'm inclined towards NOFIX due to the status of the project and the fact that we're not using a fallback oracle for the foreseeable future.

**Review by dapp-whisperer — APPROVED** [review]

**Pull request merged**
